[cli]
installer = "internal"

[ui]
max_thoughts_width = 120
fork_secondary_model = "grok-build"
yolo = false
compact_mode = true
permission_mode = "always-approve"
theme = "groknight"
keep_text_selection = "word_select"
remember_tool_approvals = true
screen_mode = "fullscreen"
show_timeline = false
collapsed_edit_blocks = true
combine_queued_prompts = true

[models]
default = "grok-composer-2.5-fast"

[marketplace]
official_marketplace_auto_installed = true
default_skills_installs_purged = true

[[marketplace.sources]]
name = "xAI Official"
git = "https://github.com/xai-org/plugin-marketplace.git"

[compat.claude]
hooks = false
skills = true
rules = true
agents = true
mcps = true

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.slack]
command = "/opt/homebrew/bin/mcp-slack"
args = []
enabled = true

[mcp_servers.slack.env]
SLACK_MCP_XOXB_TOKEN = "${SLACK_MCP_XOXB_TOKEN}"
SLACK_MCP_TEAM_ID = "T01B7BY5ULB"
