#!/bin/bash
# I Ching hexagram of the day - seeded by date

# Hexagram data: number, name, unicode
HEXAGRAMS=(
    "䷀:qian:creative"
    "䷁:kun:receptive"
    "䷂:zhun:difficulty"
    "䷃:meng:youthful"
    "䷄:xu:waiting"
    "䷅:song:conflict"
    "䷆:shi:army"
    "䷇:bi:holding"
    "䷈:xiaoxu:small"
    "䷉:lü:treading"
    "䷊:tai:peace"
    "䷋:pi:standstill"
    "䷌:tongren:fellowship"
    "䷍:dayou:abundance"
    "䷎:qian:modesty"
    "䷏:yu:enthusiasm"
    "䷐:sui:following"
    "䷑:gu:decay"
    "䷒:lin:approach"
    "䷓:guan:contemplation"
    "䷔:shihe:biting"
    "䷕:bi:grace"
    "䷖:bo:splitting"
    "䷗:fu:return"
    "䷘:wuwang:innocence"
    "䷙:daxu:taming"
    "䷚:yi:nourishing"
    "䷛:daguo:excess"
    "䷜:kan:abysmal"
    "䷝:li:clinging"
    "䷞:xian:influence"
    "䷟:heng:duration"
    "䷠:dun:retreat"
    "䷡:dazhuang:power"
    "䷢:jin:progress"
    "䷣:mingyi:darkening"
    "䷤:jiaren:family"
    "䷥:kui:opposition"
    "䷦:jian:obstruction"
    "䷧:jie:deliverance"
    "䷨:sun:decrease"
    "䷩:yi:increase"
    "䷪:guai:breakthrough"
    "䷫:gou:coming"
    "䷬:cui:gathering"
    "䷭:sheng:ascending"
    "䷮:kun:oppression"
    "䷯:jing:well"
    "䷰:ge:revolution"
    "䷱:ding:cauldron"
    "䷲:zhen:arousing"
    "䷳:gen:stillness"
    "䷴:jian:development"
    "䷵:guimei:marrying"
    "䷶:feng:fullness"
    "䷷:lü:wanderer"
    "䷸:xun:gentle"
    "䷹:dui:joyous"
    "䷺:huan:dispersion"
    "䷻:jie:limitation"
    "䷼:zhongfu:truth"
    "䷽:xiaoguo:small"
    "䷾:jiji:complete"
    "䷿:weiji:incomplete"
)

# Seed from date
DAY=$(date +%Y%m%d)
IDX=$((DAY % 64))

# Parse hexagram
IFS=':' read -r SYMBOL NAME MEANING <<< "${HEXAGRAMS[$IDX]}"

sketchybar --set iching icon="$SYMBOL" label="$MEANING" icon.color="0xffffffff" label.color="0xff666666"
